# Theano Basics - Start

In [153]:
import theano
from theano import tensor as T, function

import numpy as np
from pprint import pprint as pp

In [167]:
# Function Definitions

X = T.matrix('x')
Y = X ** 2
Z = T.grad(Y.sum(), X)
F = function([X],[Y,Z])

In [176]:
x = np.ones((2,2)) *3
y,z = F(x)



#### Print results

In [177]:
print(x)
print('-'*12)
print(y)
print('-'*12)
print(z)
print('-'*12)
pp(Z)

[[ 3.  3.]
 [ 3.  3.]]
------------
[[ 9.  9.]
 [ 9.  9.]]
------------
[[ 6.  6.]
 [ 6.  6.]]
------------
Elemwise{mul}.0
